<a href="https://colab.research.google.com/github/AanchalDogra/CNN/blob/main/melt_function_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Sample data setup
data = {
    "Date": ["01 April 2022", "05 April 2022", "07 May 2022"],
    "Value1": [10, 20, 60],
    "Value2": [30, 40, 80]
}

# Create the dataframe
df = pd.DataFrame(data)

# Convert the "Date" column to datetime format
df["Date"] = pd.to_datetime(df["Date"])

# Set the "Date" column as the index
df.set_index("Date", inplace=True)

# Generate the missing dates and duplicate the rows
date_range = pd.date_range(start=df.index.min(), end=df.index.max(), freq='D')
new_df = df.reindex(date_range)

In [ ]:
new_df

            Value1  Value2
2022-04-01    10.0    30.0
2022-04-02     NaN     NaN
2022-04-03     NaN     NaN
2022-04-04     NaN     NaN
2022-04-05    20.0    40.0
2022-04-06     NaN     NaN
2022-04-07     NaN     NaN
2022-04-08     NaN     NaN
2022-04-09     NaN     NaN
2022-04-10     NaN     NaN
2022-04-11     NaN     NaN
2022-04-12     NaN     NaN
2022-04-13     NaN     NaN
2022-04-14     NaN     NaN
2022-04-15     NaN     NaN
2022-04-16     NaN     NaN
2022-04-17     NaN     NaN
2022-04-18     NaN     NaN
2022-04-19     NaN     NaN
2022-04-20     NaN     NaN
2022-04-21     NaN     NaN
2022-04-22     NaN     NaN
2022-04-23     NaN     NaN
2022-04-24     NaN     NaN
2022-04-25     NaN     NaN
2022-04-26     NaN     NaN
2022-04-27     NaN     NaN
2022-04-28     NaN     NaN
2022-04-29     NaN     NaN
2022-04-30     NaN     NaN
2022-05-01     NaN     NaN
2022-05-02     NaN     NaN
2022-05-03     NaN     NaN
2022-05-04     NaN     NaN
2022-05-05     NaN     NaN
2022-05-06     NaN     NaN
2022-05-07    60.0    80.0